name = "client"
version = "1.0.0"
target = "javascript"
dev-dependencies = { lustre_dev_tools = ">= 1.9.2 and < 2.0.0" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.3.2 and < 6.0.0"
plinth = ">= 0.7.2 and < 1.0.0"
rsvp = ">= 1.1.3 and < 2.0.0"
gleam_http = ">= 4.1.1 and < 5.0.0"
sketch = ">= 4.2.0 and < 5.0.0"
sketch_lustre = ">= 3.1.1 and < 4.0.0"
